# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295a362fbb5048efa7f2948c22bc551406848492f5b746bce13886e818aa70fb78e7ec429991f212260ffc556856fc7a91c46248e19ab7d661110a2dd6defd8b
  gmail_password: <%= ENV["MELSCO_GMAIL_PASSWORD" %>

test:
  secret_key_base: b782bb651ab72e13957489bb13bf9a22b25ae409a9e3c99260d46c73f37f67bf6938eba4462ad67650ef14842399cdfaac3bddaf74621f6072bbd4f9024c00bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
